### ISSUE TITLE
README details

### ISSUE THREAD

**Issue by balkon16** [joanlenczuk/sktime_article#1]
Magnificent work so far, Joanna. Would be great if you could update the README file with the version of Python you're using and motivation behind your research into _sktime_. Keep up the good work ;)

**Comment by balkon16** [comment]
Just up-voting to prevent this thread from being archived. What's the ETA on closing this issue?

**Comment by joanlenczuk** [comment]
Thank you for pointing it out. I'll add all the details in README in two weeks' time. Will keep you updated!

**Comment by joanlenczuk** [comment]
Hey there, I added all the necessary details to README. Let me know if that's all you need.
